create table public.artifact (
    id bigint generated by default as identity,
    created_at timestamp
    with
        time zone not null default now (),
        title character varying null,
        data jsonb null,
        "user" text null,
        constraint artifact_pkey primary key (id),
        constraint artifact_user_fkey foreign key ("user") references users (email)
) tablespace pg_default;
