create table public.users (
    id bigint generated by default as identity,
    created_at timestamp
    with
        time zone not null default now (),
        email text not null,
        constraint users_pkey primary key (id),
        constraint users_email_key unique (email),
        constraint users_id_key unique (id)
) tablespace pg_default;
